# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-09-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='affiliate_url',
            field=models.URLField(blank=True),
        ),
    ]
